[workspace]
members = [
    "circle_packing",
    "piet_mondrian",
    "cubic_disarray",
    "joy_division",
    "mandelbrot",
    "tiled_lines",
    "julia_fractal",
    "triangular_mesh",
]
resolver = "2"
